### ISSUE TITLE
Unable to export CSV invalid-bind error

### ISSUE THREAD

**Issue by vvgh21** [jorgeuos/DataExport#6]
I get the following error when trying to use the plugin whether used through the UI or through the API: 
Error exporting data to CSV: Invalid bind-variable name ':00'
Could you please help with this
Thank you
Feel free to reply if anything else is needed from my end

**Comment by vvgh21** [comment]
@jorgeuos can you help here?

**Comment by jorgeuos** [comment]
Hi,

I saw the issue but forgot to reply.
I'll take a look over the weekend.

Hold tight!

**Comment by vvgh21** [comment]
@jorgeuos Could you check?

**Comment by jorgeuos** [comment]
Yes, sorry,

I haven't forgotten, just been really busy.

I'll take a look today.

**Comment by jorgeuos** [comment]
Hi,

I couldn't replicate the error, could you provide me with more information?

Server type
PHP version
etc..

The error:
```
Invalid bind-variable name ':00'
```

Suggests that there's a binding issue with SQL query in PHP, are you perhaps using the wrong Date format?
Should be YYYY-MM-DD

Perhaps your browser is trying to set a different format.


I also fixed some unrelated issues, could that probably solve this issue too?

Sincerely,
Jorge

**Comment by vvgh21** [comment]
Unfortunately, the update didnt fix the issue. 
The format seems to be correct in the query executed, here's a snippet from log viewer: 
<img width="708" alt="Screenshot 2024-11-23 at 8 50 18 AM" src="https://github.com/user-attachments/assets/b6b733bf-b44a-471a-b072-ed53ddbd8585">
Let me get back to you with the server details

**Comment by jorgeuos** [comment]
I made some updates in the DB query to use positional statements, I wasn't using bind parameters because it's likely that Matomo's abstraction is doing something that makes it break, at least for me.

But if you could try to update the plugin again and report back if it's working now would be good.

Otherwise it might be some DB specific issue. Are you using MySQL or MariaDB(or other).

Sincerely,
Jorge

**Comment by vvgh21** [comment]
we are using MariaDB.
Post the update, I am getting this error: 
![Screenshot 2024-11-26 at 10 22 28 AM](https://github.com/user-attachments/assets/6943dca1-db55-44a7-a2d8-26f249b68d63)

**Comment by jorgeuos** [comment]
That's not good!

I can add checks to fail more gracefully, but it seems like the path is not writeable by your server.

Could you log the output of the $fullPath variable?

Are you able to do a regular back, not csv? That might generate the backup folder.
I have a `ensure_directory_exists` function in the other functions, I just realized that I'm not using it for the CSV path, but it should be the same, so I will fix that.

Br, Jorge

**Comment by vvgh21** [comment]
I am able to download the DB dump using the plugin. And once I did a DB dump am now able to export CSVs as well. What could have been the issue

**Comment by jorgeuos** [comment]
Hi!

And thank you for the update and for confirming that the issue is resolved after performing a DB dump.

Here’s what might have happened:

The first issue that you reported was associated with:

```
Error exporting data to CSV: Invalid bind-variable name ':00'
```

was likely due to how Matomo handles PDO parameter binding. I switched to using positional parameters instead of named parameters to align better with Matomo’s abstractions. This fix addressed that specific query-related problem.

The second issue, stating that:
```
fputcsv(): Argument #1 ($stream) must be of type resource, bool given
```

indicated that the $fullPath variable didn’t point to a writable file. This happened because:

- The function `fopen($fullPath, 'w')` tried to create the file but failed, likely due to the absence of the parent directory. When the directory doesn’t exist, fopen returns false, causing the subsequent `fputcsv` call to fail.
- In the DB dump process, the file path and its parent directory are explicitly checked and created if necessary. However, this step was unintentionally missed in the CSV export feature.

I’ll ensure that the CSV export process uses the same `ensure_directory_exists` logic as the DB dump to avoid this in the future. In your case, running the DB dump created the necessary backup folder, which is why the CSV export started working afterward.

Thank you for helping me identify this improvement! Let me know if you encounter anything else.

Best regards,
Jorge

**Comment by vvgh21** [comment]
Thank you @jorgeuos

**Comment by jorgeuos** [comment]
No problem!

I have updated to a new version 1.1.8 that has the directory check in the CSV feature.

Sincerely, Jorge
